#!/usr/bin/env python3
"""Generate a deterministic Markdown index of the repository's source projects."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


MARKER = "<!-- Generated by scripts/generate_catalog.py; do not edit manually. -->"
NON_PROJECT_DIRECTORY_NAMES = frozenset({"comparisons"})


def visible_directories(path: Path) -> list[Path]:
    return sorted(
        (
            child
            for child in path.iterdir()
            if child.is_dir()
            and not child.name.startswith((".", "_"))
            and child.name not in NON_PROJECT_DIRECTORY_NAMES
        ),
        key=lambda child: child.name,
    )


def build_catalog(repo_root: Path) -> str:
    sources = repo_root / "sources"
    collections = visible_directories(sources)
    rows: list[tuple[str, str, str, str]] = []
    collection_counts: list[tuple[str, int]] = []

    for collection in collections:
        total = 0
        for date_dir in visible_directories(collection):
            projects = visible_directories(date_dir)
            total += len(projects)
            date_files = sorted(child.name for child in date_dir.iterdir() if child.is_file())
            for project in projects:
                relative = project.relative_to(repo_root).as_posix()
                rows.append((collection.name, date_dir.name, project.name, relative))
            if date_files:
                rows.append((collection.name, date_dir.name, "", ", ".join(date_files)))
        collection_counts.append((collection.name, total))

    total_projects = sum(count for _, count in collection_counts)
    lines = [
        "# Source catalog",
        "",
        MARKER,
        "",
        f"Projects: **{total_projects}** across **{len(collections)}** collections.",
        "",
        "This index is generated from direct project directories under each collection/date directory.",
        "Underscore-prefixed control directories and nested implementation folders are intentionally omitted.",
        "",
        "## Counts by collection",
        "",
        "| Collection | Projects |",
        "| --- | ---: |",
    ]
    lines.extend(f"| `{name}` | {count} |" for name, count in collection_counts)
    lines.extend(["", "## Projects", ""])

    current_collection = ""
    current_date = ""
    for collection, date, project, value in rows:
        if collection != current_collection:
            lines.extend([f"### `{collection}`", ""])
            current_collection = collection
            current_date = ""
        if date != current_date:
            lines.extend([f"#### `{date}`", ""])
            current_date = date
        if project:
            lines.append(f"- [`{project}`]({value}/)")
        else:
            lines.append(f"- Date-level artifacts: `{value}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=None, help="catalog path, relative to the repository root")
    parser.add_argument("--check", action="store_true", help="check whether the catalog is current without writing")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    output = args.output or repo_root / "CATALOG.md"
    if not output.is_absolute():
        output = repo_root / output
    expected = build_catalog(repo_root)

    if args.check:
        actual = output.read_text(encoding="utf-8") if output.exists() else ""
        if actual != expected:
            print(f"Catalog is stale: {output}", file=sys.stderr)
            return 1
        print(f"Catalog is current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())